//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 11:03:36 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.itm.uni-luebeck.de/users/kleine/isense-static-routing")
package de.uniluebeck.itm.codegeneration.isense.routing.xml.jaxb;
