//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 11:03:36 AM MEZ 
//


package de.uniluebeck.itm.codegeneration.isense.routing.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouterConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouterConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="router" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultRoute" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="routingEntry" type="{http://www.itm.uni-luebeck.de/users/kleine/isense-static-routing}RoutingEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouterConfigType", propOrder = {
    "router",
    "defaultRoute",
    "routingEntry"
})
public class RouterConfigType {

    @XmlElement(required = true)
    protected String router;
    @XmlElement(required = true)
    protected String defaultRoute;
    protected List<RoutingEntryType> routingEntry;

    /**
     * Gets the value of the router property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouter() {
        return router;
    }

    /**
     * Sets the value of the router property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouter(String value) {
        this.router = value;
    }

    /**
     * Gets the value of the defaultRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultRoute() {
        return defaultRoute;
    }

    /**
     * Sets the value of the defaultRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultRoute(String value) {
        this.defaultRoute = value;
    }

    /**
     * Gets the value of the routingEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routingEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoutingEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoutingEntryType }
     * 
     * 
     */
    public List<RoutingEntryType> getRoutingEntry() {
        if (routingEntry == null) {
            routingEntry = new ArrayList<RoutingEntryType>();
        }
        return this.routingEntry;
    }

}
